version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-animals
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: animal_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis-animals
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka-container
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper-container
    ports:
      - "2181:2181"

volumes:
  postgres_data:
  redis_data: