spring:
  datasource:
    url: jdbc:postgresql://qa-db-host:5432/animal_db
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:qa_password}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  data:
    redis:
      host: qa-redis-host
      port: 6379
  kafka:
    bootstrap-servers: qa-kafka-host:9092

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
    properties:
      org:
        quartz:
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            tablePrefix: QRTZ_
          threadPool:
            threadCount: 5

# Moderated logging for QA
logging:
  level:
    com.example.spring_project: INFO
    org.springframework.cache: WARN
    org.hibernate.SQL: WARN
    root: INFO